# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/GitHub/STM32_study/STM32_study/fpga_chuankou/chuankou/chuankou.cache/wt [current_project]
set_property parent.project_path F:/GitHub/STM32_study/STM32_study/fpga_chuankou/chuankou/chuankou.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  F:/GitHub/STM32_study/STM32_study/fpga_chuankou/chuankou/chuankou.srcs/sources_1/new/tx_control_module.v
  F:/GitHub/STM32_study/STM32_study/fpga_chuankou/chuankou/chuankou.srcs/sources_1/new/tx_bps_module.v
  F:/GitHub/STM32_study/STM32_study/fpga_chuankou/chuankou/chuankou.srcs/sources_1/new/tx_module.v
  F:/GitHub/STM32_study/STM32_study/fpga_chuankou/chuankou/chuankou.srcs/sources_1/new/control_module.v
  F:/GitHub/STM32_study/STM32_study/fpga_chuankou/chuankou/chuankou.srcs/sources_1/new/tx_module_demo.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/GitHub/STM32_study/STM32_study/fpga_chuankou/chuankou/chuankou.srcs/constrs_1/new/defence.xdc
set_property used_in_implementation false [get_files F:/GitHub/STM32_study/STM32_study/fpga_chuankou/chuankou/chuankou.srcs/constrs_1/new/defence.xdc]


synth_design -top tx_module_demo -part xc7a35tcpg236-1


write_checkpoint -force -noxdef tx_module_demo.dcp

catch { report_utilization -file tx_module_demo_utilization_synth.rpt -pb tx_module_demo_utilization_synth.pb }
